For example, lets take this example of calories from 4 different food:
                     Apples  Beef  Eggs  Potatoes

Carb                56.0    0.0   4.4    68.0

Protein               1.2   104.0  52.0    8.0

Fat                   1.8   135.0  99.0    0.9

Lets calculate the % of calories for Carb, Protein, Fat 
For each of those food WITHOUT using an explicit for-loop
By implementing Vectorization:

In [3]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


The dimension of that list is:

In [2]:
print(A.shape)

(3, 4)


First, we will do a vertical sum of the arrays so that we can get the total calorie of each of the food items:

In [4]:
cal = A.sum(axis=0) # Vertical axis
print(cal)

[ 59.  239.  155.4  76.9]


Now, we will calculate percentage of each calorie type like so:

In [8]:
percentage = 100*A/cal.reshape(1,4) # The reshape is redundent but its there for future reference
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


And there you go. Percentages calculated without using an explicit for-loop